version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "acg-challenge"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-52zwe6qwoev6"
s3_prefix = "acg-challenge"
region = "eu-central-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
profile = "folkisz"
